"""20250518_change

Revision ID: cb74df054fa6
Revises: 6ac8d46c9147
Create Date: 2025-05-18 08:54:11.242473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb74df054fa6"
down_revision: Union[str, None] = "6ac8d46c9147"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("title", sa.String(), nullable=True))
    op.drop_column("transactions", "name")
    op.drop_column("transactions", "note")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("note", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("transactions", "title")
    # ### end Alembic commands ###
