"""20250518_change

Revision ID: f6ceeb442d6e
Revises: cb74df054fa6
Create Date: 2025-05-18 09:11:33.105153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ceeb442d6e'
down_revision: Union[str, None] = 'cb74df054fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('memo', sa.String(), nullable=True))
    op.drop_column('transactions', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'memo')
    # ### end Alembic commands ###
